mkdir ttt_numerator;
cd ttt_numerator;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/data.root ttt; 
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/qqww.root ttt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/singletop.root ttt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/tother.root ttt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/ttbar.root ttt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/ttv.root ttt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/tw.root ttt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/tz.root ttt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/vvv.root ttt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/wz.root ttt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/zgam.root ttt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/zjet.root ttt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/NumeratorSelection_mc15b/fetch/data-SKIM/zz.root ttt;
cd ..;
mkdir ltt_denominator;
cd ltt_denominator;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/data.root ltt; 
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/qqww.root ltt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/singletop.root ltt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/tother.root ltt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/ttbar.root ltt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/ttv.root ltt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/tw.root ltt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/tz.root ltt;
#testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/vvv.root ltt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/wz.root ltt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/zgam.root ltt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/zjet.root ltt;
testZplusJetsWithPSLFakeNtuples ~/orig_PSL_WZ/run/FakesSelection_mc15b/fetch/data-SKIM/zz.root ltt;
cd ..;
