PACKAGE          = LeptonFakeFactorTools
PACKAGE_PRELOAD  = 
PACKAGE_CXXFLAGS =
PACKAGE_LDFLAGS  = $(shell root-config --libs --cflags) -l TreePlayer
PACKAGE_BINFLAGS = 
PACKAGE_TRYDEP   = 
PACKAGE_DEP      = AsgTools xAODEventInfo xAODEgamma xAODMuon xAODMissingET
PACKAGE_NOOPT    = 0
PACKAGE_NOCC     = 0
PACKAGE_PEDANTIC = 1
PACKAGE_REFLEX   = 0
include $(ROOTCOREDIR)/Makefile-common
